// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: tensorflow/core/debug/debugger_event_metadata.proto
#ifndef GRPC_tensorflow_2fcore_2fdebug_2fdebugger_5fevent_5fmetadata_2eproto__INCLUDED
#define GRPC_tensorflow_2fcore_2fdebug_2fdebugger_5fevent_5fmetadata_2eproto__INCLUDED

#include "tensorflow/core/debug/debugger_event_metadata.pb.h"

#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace third_party {
namespace tensorflow {
namespace core {
namespace debug {

}  // namespace debug
}  // namespace core
}  // namespace tensorflow
}  // namespace third_party


#endif  // GRPC_tensorflow_2fcore_2fdebug_2fdebugger_5fevent_5fmetadata_2eproto__INCLUDED
