// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/protobuf/critical_section.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "tensorflow/core/protobuf/critical_section.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace tensorflow {
class CriticalSectionDefDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<CriticalSectionDef>
     _instance;
} _CriticalSectionDef_default_instance_;
class CriticalSectionExecutionDefDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<CriticalSectionExecutionDef>
     _instance;
} _CriticalSectionExecutionDef_default_instance_;

namespace protobuf_tensorflow_2fcore_2fprotobuf_2fcritical_5fsection_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[2];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { NULL, NULL, 0, -1, -1, -1, -1, NULL, false },
  { NULL, NULL, 0, -1, -1, -1, -1, NULL, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CriticalSectionDef, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CriticalSectionDef, critical_section_name_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CriticalSectionExecutionDef, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CriticalSectionExecutionDef, execute_in_critical_section_name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(CriticalSectionExecutionDef, exclusive_resource_access_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(CriticalSectionDef)},
  { 6, -1, sizeof(CriticalSectionExecutionDef)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_CriticalSectionDef_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_CriticalSectionExecutionDef_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "tensorflow/core/protobuf/critical_section.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

}  // namespace
void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _CriticalSectionDef_default_instance_._instance.DefaultConstruct();
  ::google::protobuf::internal::OnShutdownDestroyMessage(
      &_CriticalSectionDef_default_instance_);_CriticalSectionExecutionDef_default_instance_._instance.DefaultConstruct();
  ::google::protobuf::internal::OnShutdownDestroyMessage(
      &_CriticalSectionExecutionDef_default_instance_);}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
namespace {
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n/tensorflow/core/protobuf/critical_sect"
      "ion.proto\022\ntensorflow\"3\n\022CriticalSection"
      "Def\022\035\n\025critical_section_name\030\001 \001(\t\"j\n\033Cr"
      "iticalSectionExecutionDef\022(\n execute_in_"
      "critical_section_name\030\001 \001(\t\022!\n\031exclusive"
      "_resource_access\030\002 \001(\010Bt\n\030org.tensorflow"
      ".frameworkB\025CriticalSectionProtosP\001Z<git"
      "hub.com/tensorflow/tensorflow/tensorflow"
      "/go/core/protobuf\370\001\001b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 348);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "tensorflow/core/protobuf/critical_section.proto", &protobuf_RegisterTypes);
}
} // anonymous namespace

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_tensorflow_2fcore_2fprotobuf_2fcritical_5fsection_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CriticalSectionDef::kCriticalSectionNameFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CriticalSectionDef::CriticalSectionDef()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_tensorflow_2fcore_2fprotobuf_2fcritical_5fsection_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:tensorflow.CriticalSectionDef)
}
CriticalSectionDef::CriticalSectionDef(::google::protobuf::Arena* arena)
  : ::google::protobuf::Message(),
  _internal_metadata_(arena) {
  protobuf_tensorflow_2fcore_2fprotobuf_2fcritical_5fsection_2eproto::InitDefaults();
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:tensorflow.CriticalSectionDef)
}
CriticalSectionDef::CriticalSectionDef(const CriticalSectionDef& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  critical_section_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.critical_section_name().size() > 0) {
    critical_section_name_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.critical_section_name(),
      GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(copy_constructor:tensorflow.CriticalSectionDef)
}

void CriticalSectionDef::SharedCtor() {
  critical_section_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _cached_size_ = 0;
}

CriticalSectionDef::~CriticalSectionDef() {
  // @@protoc_insertion_point(destructor:tensorflow.CriticalSectionDef)
  SharedDtor();
}

void CriticalSectionDef::SharedDtor() {
  ::google::protobuf::Arena* arena = GetArenaNoVirtual();
  GOOGLE_DCHECK(arena == NULL);
  if (arena != NULL) {
    return;
  }

  critical_section_name_.Destroy(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), arena);
}

void CriticalSectionDef::ArenaDtor(void* object) {
  CriticalSectionDef* _this = reinterpret_cast< CriticalSectionDef* >(object);
  (void)_this;
}
void CriticalSectionDef::RegisterArenaDtor(::google::protobuf::Arena* arena) {
}
void CriticalSectionDef::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CriticalSectionDef::descriptor() {
  protobuf_tensorflow_2fcore_2fprotobuf_2fcritical_5fsection_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_tensorflow_2fcore_2fprotobuf_2fcritical_5fsection_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const CriticalSectionDef& CriticalSectionDef::default_instance() {
  protobuf_tensorflow_2fcore_2fprotobuf_2fcritical_5fsection_2eproto::InitDefaults();
  return *internal_default_instance();
}

CriticalSectionDef* CriticalSectionDef::New(::google::protobuf::Arena* arena) const {
  return ::google::protobuf::Arena::CreateMessage<CriticalSectionDef>(arena);
}

void CriticalSectionDef::Clear() {
// @@protoc_insertion_point(message_clear_start:tensorflow.CriticalSectionDef)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  critical_section_name_.ClearToEmpty(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
  _internal_metadata_.Clear();
}

bool CriticalSectionDef::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:tensorflow.CriticalSectionDef)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string critical_section_name = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_critical_section_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->critical_section_name().data(), static_cast<int>(this->critical_section_name().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "tensorflow.CriticalSectionDef.critical_section_name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:tensorflow.CriticalSectionDef)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:tensorflow.CriticalSectionDef)
  return false;
#undef DO_
}

void CriticalSectionDef::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:tensorflow.CriticalSectionDef)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string critical_section_name = 1;
  if (this->critical_section_name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->critical_section_name().data(), static_cast<int>(this->critical_section_name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "tensorflow.CriticalSectionDef.critical_section_name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->critical_section_name(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:tensorflow.CriticalSectionDef)
}

::google::protobuf::uint8* CriticalSectionDef::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:tensorflow.CriticalSectionDef)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string critical_section_name = 1;
  if (this->critical_section_name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->critical_section_name().data(), static_cast<int>(this->critical_section_name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "tensorflow.CriticalSectionDef.critical_section_name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->critical_section_name(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tensorflow.CriticalSectionDef)
  return target;
}

size_t CriticalSectionDef::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tensorflow.CriticalSectionDef)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string critical_section_name = 1;
  if (this->critical_section_name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->critical_section_name());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CriticalSectionDef::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:tensorflow.CriticalSectionDef)
  GOOGLE_DCHECK_NE(&from, this);
  const CriticalSectionDef* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const CriticalSectionDef>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:tensorflow.CriticalSectionDef)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:tensorflow.CriticalSectionDef)
    MergeFrom(*source);
  }
}

void CriticalSectionDef::MergeFrom(const CriticalSectionDef& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:tensorflow.CriticalSectionDef)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.critical_section_name().size() > 0) {
    set_critical_section_name(from.critical_section_name());
  }
}

void CriticalSectionDef::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:tensorflow.CriticalSectionDef)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CriticalSectionDef::CopyFrom(const CriticalSectionDef& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tensorflow.CriticalSectionDef)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CriticalSectionDef::IsInitialized() const {
  return true;
}

void CriticalSectionDef::Swap(CriticalSectionDef* other) {
  if (other == this) return;
  if (GetArenaNoVirtual() == other->GetArenaNoVirtual()) {
    InternalSwap(other);
  } else {
    CriticalSectionDef* temp = New(GetArenaNoVirtual());
    temp->MergeFrom(*other);
    other->CopyFrom(*this);
    InternalSwap(temp);
    if (GetArenaNoVirtual() == NULL) {
      delete temp;
    }
  }
}
void CriticalSectionDef::UnsafeArenaSwap(CriticalSectionDef* other) {
  if (other == this) return;
  GOOGLE_DCHECK(GetArenaNoVirtual() == other->GetArenaNoVirtual());
  InternalSwap(other);
}
void CriticalSectionDef::InternalSwap(CriticalSectionDef* other) {
  using std::swap;
  critical_section_name_.Swap(&other->critical_section_name_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata CriticalSectionDef::GetMetadata() const {
  protobuf_tensorflow_2fcore_2fprotobuf_2fcritical_5fsection_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_tensorflow_2fcore_2fprotobuf_2fcritical_5fsection_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// CriticalSectionDef

// string critical_section_name = 1;
void CriticalSectionDef::clear_critical_section_name() {
  critical_section_name_.ClearToEmpty(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
const ::std::string& CriticalSectionDef::critical_section_name() const {
  // @@protoc_insertion_point(field_get:tensorflow.CriticalSectionDef.critical_section_name)
  return critical_section_name_.Get();
}
void CriticalSectionDef::set_critical_section_name(const ::std::string& value) {
  
  critical_section_name_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value, GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set:tensorflow.CriticalSectionDef.critical_section_name)
}
#if LANG_CXX11
void CriticalSectionDef::set_critical_section_name(::std::string&& value) {
  
  critical_section_name_.Set(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_rvalue:tensorflow.CriticalSectionDef.critical_section_name)
}
#endif
void CriticalSectionDef::set_critical_section_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  critical_section_name_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_char:tensorflow.CriticalSectionDef.critical_section_name)
}
void CriticalSectionDef::set_critical_section_name(const char* value,
    size_t size) {
  
  critical_section_name_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_pointer:tensorflow.CriticalSectionDef.critical_section_name)
}
::std::string* CriticalSectionDef::mutable_critical_section_name() {
  
  // @@protoc_insertion_point(field_mutable:tensorflow.CriticalSectionDef.critical_section_name)
  return critical_section_name_.Mutable(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
::std::string* CriticalSectionDef::release_critical_section_name() {
  // @@protoc_insertion_point(field_release:tensorflow.CriticalSectionDef.critical_section_name)
  
  return critical_section_name_.Release(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
::std::string* CriticalSectionDef::unsafe_arena_release_critical_section_name() {
  // @@protoc_insertion_point(field_unsafe_arena_release:tensorflow.CriticalSectionDef.critical_section_name)
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  
  return critical_section_name_.UnsafeArenaRelease(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      GetArenaNoVirtual());
}
void CriticalSectionDef::set_allocated_critical_section_name(::std::string* critical_section_name) {
  if (critical_section_name != NULL) {
    
  } else {
    
  }
  critical_section_name_.SetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), critical_section_name,
      GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_allocated:tensorflow.CriticalSectionDef.critical_section_name)
}
void CriticalSectionDef::unsafe_arena_set_allocated_critical_section_name(
    ::std::string* critical_section_name) {
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  if (critical_section_name != NULL) {
    
  } else {
    
  }
  critical_section_name_.UnsafeArenaSetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      critical_section_name, GetArenaNoVirtual());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:tensorflow.CriticalSectionDef.critical_section_name)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CriticalSectionExecutionDef::kExecuteInCriticalSectionNameFieldNumber;
const int CriticalSectionExecutionDef::kExclusiveResourceAccessFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CriticalSectionExecutionDef::CriticalSectionExecutionDef()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_tensorflow_2fcore_2fprotobuf_2fcritical_5fsection_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:tensorflow.CriticalSectionExecutionDef)
}
CriticalSectionExecutionDef::CriticalSectionExecutionDef(::google::protobuf::Arena* arena)
  : ::google::protobuf::Message(),
  _internal_metadata_(arena) {
  protobuf_tensorflow_2fcore_2fprotobuf_2fcritical_5fsection_2eproto::InitDefaults();
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:tensorflow.CriticalSectionExecutionDef)
}
CriticalSectionExecutionDef::CriticalSectionExecutionDef(const CriticalSectionExecutionDef& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  execute_in_critical_section_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.execute_in_critical_section_name().size() > 0) {
    execute_in_critical_section_name_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.execute_in_critical_section_name(),
      GetArenaNoVirtual());
  }
  exclusive_resource_access_ = from.exclusive_resource_access_;
  // @@protoc_insertion_point(copy_constructor:tensorflow.CriticalSectionExecutionDef)
}

void CriticalSectionExecutionDef::SharedCtor() {
  execute_in_critical_section_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  exclusive_resource_access_ = false;
  _cached_size_ = 0;
}

CriticalSectionExecutionDef::~CriticalSectionExecutionDef() {
  // @@protoc_insertion_point(destructor:tensorflow.CriticalSectionExecutionDef)
  SharedDtor();
}

void CriticalSectionExecutionDef::SharedDtor() {
  ::google::protobuf::Arena* arena = GetArenaNoVirtual();
  GOOGLE_DCHECK(arena == NULL);
  if (arena != NULL) {
    return;
  }

  execute_in_critical_section_name_.Destroy(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), arena);
}

void CriticalSectionExecutionDef::ArenaDtor(void* object) {
  CriticalSectionExecutionDef* _this = reinterpret_cast< CriticalSectionExecutionDef* >(object);
  (void)_this;
}
void CriticalSectionExecutionDef::RegisterArenaDtor(::google::protobuf::Arena* arena) {
}
void CriticalSectionExecutionDef::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* CriticalSectionExecutionDef::descriptor() {
  protobuf_tensorflow_2fcore_2fprotobuf_2fcritical_5fsection_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_tensorflow_2fcore_2fprotobuf_2fcritical_5fsection_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const CriticalSectionExecutionDef& CriticalSectionExecutionDef::default_instance() {
  protobuf_tensorflow_2fcore_2fprotobuf_2fcritical_5fsection_2eproto::InitDefaults();
  return *internal_default_instance();
}

CriticalSectionExecutionDef* CriticalSectionExecutionDef::New(::google::protobuf::Arena* arena) const {
  return ::google::protobuf::Arena::CreateMessage<CriticalSectionExecutionDef>(arena);
}

void CriticalSectionExecutionDef::Clear() {
// @@protoc_insertion_point(message_clear_start:tensorflow.CriticalSectionExecutionDef)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  execute_in_critical_section_name_.ClearToEmpty(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
  exclusive_resource_access_ = false;
  _internal_metadata_.Clear();
}

bool CriticalSectionExecutionDef::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:tensorflow.CriticalSectionExecutionDef)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string execute_in_critical_section_name = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_execute_in_critical_section_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->execute_in_critical_section_name().data(), static_cast<int>(this->execute_in_critical_section_name().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "tensorflow.CriticalSectionExecutionDef.execute_in_critical_section_name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool exclusive_resource_access = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &exclusive_resource_access_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:tensorflow.CriticalSectionExecutionDef)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:tensorflow.CriticalSectionExecutionDef)
  return false;
#undef DO_
}

void CriticalSectionExecutionDef::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:tensorflow.CriticalSectionExecutionDef)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string execute_in_critical_section_name = 1;
  if (this->execute_in_critical_section_name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->execute_in_critical_section_name().data(), static_cast<int>(this->execute_in_critical_section_name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "tensorflow.CriticalSectionExecutionDef.execute_in_critical_section_name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->execute_in_critical_section_name(), output);
  }

  // bool exclusive_resource_access = 2;
  if (this->exclusive_resource_access() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(2, this->exclusive_resource_access(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:tensorflow.CriticalSectionExecutionDef)
}

::google::protobuf::uint8* CriticalSectionExecutionDef::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:tensorflow.CriticalSectionExecutionDef)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string execute_in_critical_section_name = 1;
  if (this->execute_in_critical_section_name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->execute_in_critical_section_name().data(), static_cast<int>(this->execute_in_critical_section_name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "tensorflow.CriticalSectionExecutionDef.execute_in_critical_section_name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->execute_in_critical_section_name(), target);
  }

  // bool exclusive_resource_access = 2;
  if (this->exclusive_resource_access() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(2, this->exclusive_resource_access(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tensorflow.CriticalSectionExecutionDef)
  return target;
}

size_t CriticalSectionExecutionDef::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tensorflow.CriticalSectionExecutionDef)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string execute_in_critical_section_name = 1;
  if (this->execute_in_critical_section_name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->execute_in_critical_section_name());
  }

  // bool exclusive_resource_access = 2;
  if (this->exclusive_resource_access() != 0) {
    total_size += 1 + 1;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void CriticalSectionExecutionDef::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:tensorflow.CriticalSectionExecutionDef)
  GOOGLE_DCHECK_NE(&from, this);
  const CriticalSectionExecutionDef* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const CriticalSectionExecutionDef>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:tensorflow.CriticalSectionExecutionDef)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:tensorflow.CriticalSectionExecutionDef)
    MergeFrom(*source);
  }
}

void CriticalSectionExecutionDef::MergeFrom(const CriticalSectionExecutionDef& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:tensorflow.CriticalSectionExecutionDef)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.execute_in_critical_section_name().size() > 0) {
    set_execute_in_critical_section_name(from.execute_in_critical_section_name());
  }
  if (from.exclusive_resource_access() != 0) {
    set_exclusive_resource_access(from.exclusive_resource_access());
  }
}

void CriticalSectionExecutionDef::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:tensorflow.CriticalSectionExecutionDef)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CriticalSectionExecutionDef::CopyFrom(const CriticalSectionExecutionDef& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tensorflow.CriticalSectionExecutionDef)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CriticalSectionExecutionDef::IsInitialized() const {
  return true;
}

void CriticalSectionExecutionDef::Swap(CriticalSectionExecutionDef* other) {
  if (other == this) return;
  if (GetArenaNoVirtual() == other->GetArenaNoVirtual()) {
    InternalSwap(other);
  } else {
    CriticalSectionExecutionDef* temp = New(GetArenaNoVirtual());
    temp->MergeFrom(*other);
    other->CopyFrom(*this);
    InternalSwap(temp);
    if (GetArenaNoVirtual() == NULL) {
      delete temp;
    }
  }
}
void CriticalSectionExecutionDef::UnsafeArenaSwap(CriticalSectionExecutionDef* other) {
  if (other == this) return;
  GOOGLE_DCHECK(GetArenaNoVirtual() == other->GetArenaNoVirtual());
  InternalSwap(other);
}
void CriticalSectionExecutionDef::InternalSwap(CriticalSectionExecutionDef* other) {
  using std::swap;
  execute_in_critical_section_name_.Swap(&other->execute_in_critical_section_name_);
  swap(exclusive_resource_access_, other->exclusive_resource_access_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata CriticalSectionExecutionDef::GetMetadata() const {
  protobuf_tensorflow_2fcore_2fprotobuf_2fcritical_5fsection_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_tensorflow_2fcore_2fprotobuf_2fcritical_5fsection_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// CriticalSectionExecutionDef

// string execute_in_critical_section_name = 1;
void CriticalSectionExecutionDef::clear_execute_in_critical_section_name() {
  execute_in_critical_section_name_.ClearToEmpty(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
const ::std::string& CriticalSectionExecutionDef::execute_in_critical_section_name() const {
  // @@protoc_insertion_point(field_get:tensorflow.CriticalSectionExecutionDef.execute_in_critical_section_name)
  return execute_in_critical_section_name_.Get();
}
void CriticalSectionExecutionDef::set_execute_in_critical_section_name(const ::std::string& value) {
  
  execute_in_critical_section_name_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value, GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set:tensorflow.CriticalSectionExecutionDef.execute_in_critical_section_name)
}
#if LANG_CXX11
void CriticalSectionExecutionDef::set_execute_in_critical_section_name(::std::string&& value) {
  
  execute_in_critical_section_name_.Set(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_rvalue:tensorflow.CriticalSectionExecutionDef.execute_in_critical_section_name)
}
#endif
void CriticalSectionExecutionDef::set_execute_in_critical_section_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  execute_in_critical_section_name_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_char:tensorflow.CriticalSectionExecutionDef.execute_in_critical_section_name)
}
void CriticalSectionExecutionDef::set_execute_in_critical_section_name(const char* value,
    size_t size) {
  
  execute_in_critical_section_name_.Set(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_pointer:tensorflow.CriticalSectionExecutionDef.execute_in_critical_section_name)
}
::std::string* CriticalSectionExecutionDef::mutable_execute_in_critical_section_name() {
  
  // @@protoc_insertion_point(field_mutable:tensorflow.CriticalSectionExecutionDef.execute_in_critical_section_name)
  return execute_in_critical_section_name_.Mutable(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
::std::string* CriticalSectionExecutionDef::release_execute_in_critical_section_name() {
  // @@protoc_insertion_point(field_release:tensorflow.CriticalSectionExecutionDef.execute_in_critical_section_name)
  
  return execute_in_critical_section_name_.Release(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
}
::std::string* CriticalSectionExecutionDef::unsafe_arena_release_execute_in_critical_section_name() {
  // @@protoc_insertion_point(field_unsafe_arena_release:tensorflow.CriticalSectionExecutionDef.execute_in_critical_section_name)
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  
  return execute_in_critical_section_name_.UnsafeArenaRelease(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      GetArenaNoVirtual());
}
void CriticalSectionExecutionDef::set_allocated_execute_in_critical_section_name(::std::string* execute_in_critical_section_name) {
  if (execute_in_critical_section_name != NULL) {
    
  } else {
    
  }
  execute_in_critical_section_name_.SetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), execute_in_critical_section_name,
      GetArenaNoVirtual());
  // @@protoc_insertion_point(field_set_allocated:tensorflow.CriticalSectionExecutionDef.execute_in_critical_section_name)
}
void CriticalSectionExecutionDef::unsafe_arena_set_allocated_execute_in_critical_section_name(
    ::std::string* execute_in_critical_section_name) {
  GOOGLE_DCHECK(GetArenaNoVirtual() != NULL);
  if (execute_in_critical_section_name != NULL) {
    
  } else {
    
  }
  execute_in_critical_section_name_.UnsafeArenaSetAllocated(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      execute_in_critical_section_name, GetArenaNoVirtual());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:tensorflow.CriticalSectionExecutionDef.execute_in_critical_section_name)
}

// bool exclusive_resource_access = 2;
void CriticalSectionExecutionDef::clear_exclusive_resource_access() {
  exclusive_resource_access_ = false;
}
bool CriticalSectionExecutionDef::exclusive_resource_access() const {
  // @@protoc_insertion_point(field_get:tensorflow.CriticalSectionExecutionDef.exclusive_resource_access)
  return exclusive_resource_access_;
}
void CriticalSectionExecutionDef::set_exclusive_resource_access(bool value) {
  
  exclusive_resource_access_ = value;
  // @@protoc_insertion_point(field_set:tensorflow.CriticalSectionExecutionDef.exclusive_resource_access)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace tensorflow

// @@protoc_insertion_point(global_scope)
