// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/contrib/boosted_trees/proto/split_info.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "tensorflow/contrib/boosted_trees/proto/split_info.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace tensorflow {
namespace boosted_trees {
namespace learner {
class SplitInfoDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<SplitInfo>
     _instance;
} _SplitInfo_default_instance_;

namespace protobuf_tensorflow_2fcontrib_2fboosted_5ftrees_2fproto_2fsplit_5finfo_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[1];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { NULL, NULL, 0, -1, -1, -1, -1, NULL, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SplitInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SplitInfo, split_node_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SplitInfo, left_child_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(SplitInfo, right_child_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(SplitInfo)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_SplitInfo_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "tensorflow/contrib/boosted_trees/proto/split_info.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

}  // namespace
void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  ::tensorflow::boosted_trees::trees::protobuf_tensorflow_2fcontrib_2fboosted_5ftrees_2fproto_2ftree_5fconfig_2eproto::InitDefaults();
  _SplitInfo_default_instance_._instance.DefaultConstruct();
  ::google::protobuf::internal::OnShutdownDestroyMessage(
      &_SplitInfo_default_instance_);_SplitInfo_default_instance_._instance.get_mutable()->split_node_ = const_cast< ::tensorflow::boosted_trees::trees::TreeNode*>(
      ::tensorflow::boosted_trees::trees::TreeNode::internal_default_instance());
  _SplitInfo_default_instance_._instance.get_mutable()->left_child_ = const_cast< ::tensorflow::boosted_trees::trees::Leaf*>(
      ::tensorflow::boosted_trees::trees::Leaf::internal_default_instance());
  _SplitInfo_default_instance_._instance.get_mutable()->right_child_ = const_cast< ::tensorflow::boosted_trees::trees::Leaf*>(
      ::tensorflow::boosted_trees::trees::Leaf::internal_default_instance());
}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
namespace {
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n7tensorflow/contrib/boosted_trees/proto"
      "/split_info.proto\022 tensorflow.boosted_tr"
      "ees.learner\0328tensorflow/contrib/boosted_"
      "trees/proto/tree_config.proto\"\276\001\n\tSplitI"
      "nfo\022<\n\nsplit_node\030\001 \001(\0132(.tensorflow.boo"
      "sted_trees.trees.TreeNode\0228\n\nleft_child\030"
      "\002 \001(\0132$.tensorflow.boosted_trees.trees.L"
      "eaf\0229\n\013right_child\030\003 \001(\0132$.tensorflow.bo"
      "osted_trees.trees.LeafB\003\370\001\001b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 355);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "tensorflow/contrib/boosted_trees/proto/split_info.proto", &protobuf_RegisterTypes);
  ::tensorflow::boosted_trees::trees::protobuf_tensorflow_2fcontrib_2fboosted_5ftrees_2fproto_2ftree_5fconfig_2eproto::AddDescriptors();
}
} // anonymous namespace

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_tensorflow_2fcontrib_2fboosted_5ftrees_2fproto_2fsplit_5finfo_2eproto


// ===================================================================

void SplitInfo::_slow_mutable_split_node() {
  split_node_ = ::google::protobuf::Arena::CreateMessage< ::tensorflow::boosted_trees::trees::TreeNode >(
      GetArenaNoVirtual());
}
::tensorflow::boosted_trees::trees::TreeNode* SplitInfo::_slow_release_split_node() {
  if (split_node_ == NULL) {
    return NULL;
  } else {
    ::tensorflow::boosted_trees::trees::TreeNode* temp = new ::tensorflow::boosted_trees::trees::TreeNode(*split_node_);
    split_node_ = NULL;
    return temp;
  }
}
::tensorflow::boosted_trees::trees::TreeNode* SplitInfo::unsafe_arena_release_split_node() {
  // @@protoc_insertion_point(field_unsafe_arena_release:tensorflow.boosted_trees.learner.SplitInfo.split_node)
  
  ::tensorflow::boosted_trees::trees::TreeNode* temp = split_node_;
  split_node_ = NULL;
  return temp;
}
void SplitInfo::_slow_set_allocated_split_node(
    ::google::protobuf::Arena* message_arena, ::tensorflow::boosted_trees::trees::TreeNode** split_node) {
    if (message_arena != NULL && 
        ::google::protobuf::Arena::GetArena(*split_node) == NULL) {
      message_arena->Own(*split_node);
    } else if (message_arena !=
               ::google::protobuf::Arena::GetArena(*split_node)) {
      ::tensorflow::boosted_trees::trees::TreeNode* new_split_node = 
            ::google::protobuf::Arena::CreateMessage< ::tensorflow::boosted_trees::trees::TreeNode >(
            message_arena);
      new_split_node->CopyFrom(**split_node);
      *split_node = new_split_node;
    }
}
void SplitInfo::unsafe_arena_set_allocated_split_node(
    ::tensorflow::boosted_trees::trees::TreeNode* split_node) {
  if (GetArenaNoVirtual() == NULL) {
    delete split_node_;
  }
  split_node_ = split_node;
  if (split_node) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:tensorflow.boosted_trees.learner.SplitInfo.split_node)
}
void SplitInfo::_slow_mutable_left_child() {
  left_child_ = ::google::protobuf::Arena::CreateMessage< ::tensorflow::boosted_trees::trees::Leaf >(
      GetArenaNoVirtual());
}
::tensorflow::boosted_trees::trees::Leaf* SplitInfo::_slow_release_left_child() {
  if (left_child_ == NULL) {
    return NULL;
  } else {
    ::tensorflow::boosted_trees::trees::Leaf* temp = new ::tensorflow::boosted_trees::trees::Leaf(*left_child_);
    left_child_ = NULL;
    return temp;
  }
}
::tensorflow::boosted_trees::trees::Leaf* SplitInfo::unsafe_arena_release_left_child() {
  // @@protoc_insertion_point(field_unsafe_arena_release:tensorflow.boosted_trees.learner.SplitInfo.left_child)
  
  ::tensorflow::boosted_trees::trees::Leaf* temp = left_child_;
  left_child_ = NULL;
  return temp;
}
void SplitInfo::_slow_set_allocated_left_child(
    ::google::protobuf::Arena* message_arena, ::tensorflow::boosted_trees::trees::Leaf** left_child) {
    if (message_arena != NULL && 
        ::google::protobuf::Arena::GetArena(*left_child) == NULL) {
      message_arena->Own(*left_child);
    } else if (message_arena !=
               ::google::protobuf::Arena::GetArena(*left_child)) {
      ::tensorflow::boosted_trees::trees::Leaf* new_left_child = 
            ::google::protobuf::Arena::CreateMessage< ::tensorflow::boosted_trees::trees::Leaf >(
            message_arena);
      new_left_child->CopyFrom(**left_child);
      *left_child = new_left_child;
    }
}
void SplitInfo::unsafe_arena_set_allocated_left_child(
    ::tensorflow::boosted_trees::trees::Leaf* left_child) {
  if (GetArenaNoVirtual() == NULL) {
    delete left_child_;
  }
  left_child_ = left_child;
  if (left_child) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:tensorflow.boosted_trees.learner.SplitInfo.left_child)
}
void SplitInfo::_slow_mutable_right_child() {
  right_child_ = ::google::protobuf::Arena::CreateMessage< ::tensorflow::boosted_trees::trees::Leaf >(
      GetArenaNoVirtual());
}
::tensorflow::boosted_trees::trees::Leaf* SplitInfo::_slow_release_right_child() {
  if (right_child_ == NULL) {
    return NULL;
  } else {
    ::tensorflow::boosted_trees::trees::Leaf* temp = new ::tensorflow::boosted_trees::trees::Leaf(*right_child_);
    right_child_ = NULL;
    return temp;
  }
}
::tensorflow::boosted_trees::trees::Leaf* SplitInfo::unsafe_arena_release_right_child() {
  // @@protoc_insertion_point(field_unsafe_arena_release:tensorflow.boosted_trees.learner.SplitInfo.right_child)
  
  ::tensorflow::boosted_trees::trees::Leaf* temp = right_child_;
  right_child_ = NULL;
  return temp;
}
void SplitInfo::_slow_set_allocated_right_child(
    ::google::protobuf::Arena* message_arena, ::tensorflow::boosted_trees::trees::Leaf** right_child) {
    if (message_arena != NULL && 
        ::google::protobuf::Arena::GetArena(*right_child) == NULL) {
      message_arena->Own(*right_child);
    } else if (message_arena !=
               ::google::protobuf::Arena::GetArena(*right_child)) {
      ::tensorflow::boosted_trees::trees::Leaf* new_right_child = 
            ::google::protobuf::Arena::CreateMessage< ::tensorflow::boosted_trees::trees::Leaf >(
            message_arena);
      new_right_child->CopyFrom(**right_child);
      *right_child = new_right_child;
    }
}
void SplitInfo::unsafe_arena_set_allocated_right_child(
    ::tensorflow::boosted_trees::trees::Leaf* right_child) {
  if (GetArenaNoVirtual() == NULL) {
    delete right_child_;
  }
  right_child_ = right_child;
  if (right_child) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:tensorflow.boosted_trees.learner.SplitInfo.right_child)
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SplitInfo::kSplitNodeFieldNumber;
const int SplitInfo::kLeftChildFieldNumber;
const int SplitInfo::kRightChildFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SplitInfo::SplitInfo()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_tensorflow_2fcontrib_2fboosted_5ftrees_2fproto_2fsplit_5finfo_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:tensorflow.boosted_trees.learner.SplitInfo)
}
SplitInfo::SplitInfo(::google::protobuf::Arena* arena)
  : ::google::protobuf::Message(),
  _internal_metadata_(arena) {
  protobuf_tensorflow_2fcontrib_2fboosted_5ftrees_2fproto_2fsplit_5finfo_2eproto::InitDefaults();
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:tensorflow.boosted_trees.learner.SplitInfo)
}
SplitInfo::SplitInfo(const SplitInfo& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_split_node()) {
    split_node_ = new ::tensorflow::boosted_trees::trees::TreeNode(*from.split_node_);
  } else {
    split_node_ = NULL;
  }
  if (from.has_left_child()) {
    left_child_ = new ::tensorflow::boosted_trees::trees::Leaf(*from.left_child_);
  } else {
    left_child_ = NULL;
  }
  if (from.has_right_child()) {
    right_child_ = new ::tensorflow::boosted_trees::trees::Leaf(*from.right_child_);
  } else {
    right_child_ = NULL;
  }
  // @@protoc_insertion_point(copy_constructor:tensorflow.boosted_trees.learner.SplitInfo)
}

void SplitInfo::SharedCtor() {
  ::memset(&split_node_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&right_child_) -
      reinterpret_cast<char*>(&split_node_)) + sizeof(right_child_));
  _cached_size_ = 0;
}

SplitInfo::~SplitInfo() {
  // @@protoc_insertion_point(destructor:tensorflow.boosted_trees.learner.SplitInfo)
  SharedDtor();
}

void SplitInfo::SharedDtor() {
  ::google::protobuf::Arena* arena = GetArenaNoVirtual();
  GOOGLE_DCHECK(arena == NULL);
  if (arena != NULL) {
    return;
  }

  if (this != internal_default_instance()) delete split_node_;
  if (this != internal_default_instance()) delete left_child_;
  if (this != internal_default_instance()) delete right_child_;
}

void SplitInfo::ArenaDtor(void* object) {
  SplitInfo* _this = reinterpret_cast< SplitInfo* >(object);
  (void)_this;
}
void SplitInfo::RegisterArenaDtor(::google::protobuf::Arena* arena) {
}
void SplitInfo::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SplitInfo::descriptor() {
  protobuf_tensorflow_2fcontrib_2fboosted_5ftrees_2fproto_2fsplit_5finfo_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_tensorflow_2fcontrib_2fboosted_5ftrees_2fproto_2fsplit_5finfo_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const SplitInfo& SplitInfo::default_instance() {
  protobuf_tensorflow_2fcontrib_2fboosted_5ftrees_2fproto_2fsplit_5finfo_2eproto::InitDefaults();
  return *internal_default_instance();
}

SplitInfo* SplitInfo::New(::google::protobuf::Arena* arena) const {
  return ::google::protobuf::Arena::CreateMessage<SplitInfo>(arena);
}

void SplitInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:tensorflow.boosted_trees.learner.SplitInfo)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaNoVirtual() == NULL && split_node_ != NULL) {
    delete split_node_;
  }
  split_node_ = NULL;
  if (GetArenaNoVirtual() == NULL && left_child_ != NULL) {
    delete left_child_;
  }
  left_child_ = NULL;
  if (GetArenaNoVirtual() == NULL && right_child_ != NULL) {
    delete right_child_;
  }
  right_child_ = NULL;
  _internal_metadata_.Clear();
}

bool SplitInfo::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:tensorflow.boosted_trees.learner.SplitInfo)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .tensorflow.boosted_trees.trees.TreeNode split_node = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_split_node()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .tensorflow.boosted_trees.trees.Leaf left_child = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_left_child()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .tensorflow.boosted_trees.trees.Leaf right_child = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_right_child()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:tensorflow.boosted_trees.learner.SplitInfo)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:tensorflow.boosted_trees.learner.SplitInfo)
  return false;
#undef DO_
}

void SplitInfo::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:tensorflow.boosted_trees.learner.SplitInfo)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .tensorflow.boosted_trees.trees.TreeNode split_node = 1;
  if (this->has_split_node()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, *this->split_node_, output);
  }

  // .tensorflow.boosted_trees.trees.Leaf left_child = 2;
  if (this->has_left_child()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, *this->left_child_, output);
  }

  // .tensorflow.boosted_trees.trees.Leaf right_child = 3;
  if (this->has_right_child()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, *this->right_child_, output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:tensorflow.boosted_trees.learner.SplitInfo)
}

::google::protobuf::uint8* SplitInfo::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:tensorflow.boosted_trees.learner.SplitInfo)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .tensorflow.boosted_trees.trees.TreeNode split_node = 1;
  if (this->has_split_node()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, *this->split_node_, deterministic, target);
  }

  // .tensorflow.boosted_trees.trees.Leaf left_child = 2;
  if (this->has_left_child()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        2, *this->left_child_, deterministic, target);
  }

  // .tensorflow.boosted_trees.trees.Leaf right_child = 3;
  if (this->has_right_child()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        3, *this->right_child_, deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tensorflow.boosted_trees.learner.SplitInfo)
  return target;
}

size_t SplitInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tensorflow.boosted_trees.learner.SplitInfo)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // .tensorflow.boosted_trees.trees.TreeNode split_node = 1;
  if (this->has_split_node()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->split_node_);
  }

  // .tensorflow.boosted_trees.trees.Leaf left_child = 2;
  if (this->has_left_child()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->left_child_);
  }

  // .tensorflow.boosted_trees.trees.Leaf right_child = 3;
  if (this->has_right_child()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->right_child_);
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SplitInfo::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:tensorflow.boosted_trees.learner.SplitInfo)
  GOOGLE_DCHECK_NE(&from, this);
  const SplitInfo* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const SplitInfo>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:tensorflow.boosted_trees.learner.SplitInfo)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:tensorflow.boosted_trees.learner.SplitInfo)
    MergeFrom(*source);
  }
}

void SplitInfo::MergeFrom(const SplitInfo& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:tensorflow.boosted_trees.learner.SplitInfo)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_split_node()) {
    mutable_split_node()->::tensorflow::boosted_trees::trees::TreeNode::MergeFrom(from.split_node());
  }
  if (from.has_left_child()) {
    mutable_left_child()->::tensorflow::boosted_trees::trees::Leaf::MergeFrom(from.left_child());
  }
  if (from.has_right_child()) {
    mutable_right_child()->::tensorflow::boosted_trees::trees::Leaf::MergeFrom(from.right_child());
  }
}

void SplitInfo::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:tensorflow.boosted_trees.learner.SplitInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SplitInfo::CopyFrom(const SplitInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tensorflow.boosted_trees.learner.SplitInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SplitInfo::IsInitialized() const {
  return true;
}

void SplitInfo::Swap(SplitInfo* other) {
  if (other == this) return;
  if (GetArenaNoVirtual() == other->GetArenaNoVirtual()) {
    InternalSwap(other);
  } else {
    SplitInfo* temp = New(GetArenaNoVirtual());
    temp->MergeFrom(*other);
    other->CopyFrom(*this);
    InternalSwap(temp);
    if (GetArenaNoVirtual() == NULL) {
      delete temp;
    }
  }
}
void SplitInfo::UnsafeArenaSwap(SplitInfo* other) {
  if (other == this) return;
  GOOGLE_DCHECK(GetArenaNoVirtual() == other->GetArenaNoVirtual());
  InternalSwap(other);
}
void SplitInfo::InternalSwap(SplitInfo* other) {
  using std::swap;
  swap(split_node_, other->split_node_);
  swap(left_child_, other->left_child_);
  swap(right_child_, other->right_child_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata SplitInfo::GetMetadata() const {
  protobuf_tensorflow_2fcontrib_2fboosted_5ftrees_2fproto_2fsplit_5finfo_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_tensorflow_2fcontrib_2fboosted_5ftrees_2fproto_2fsplit_5finfo_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// SplitInfo

// .tensorflow.boosted_trees.trees.TreeNode split_node = 1;
bool SplitInfo::has_split_node() const {
  return this != internal_default_instance() && split_node_ != NULL;
}
void SplitInfo::clear_split_node() {
  if (GetArenaNoVirtual() == NULL && split_node_ != NULL) delete split_node_;
  split_node_ = NULL;
}
const ::tensorflow::boosted_trees::trees::TreeNode& SplitInfo::split_node() const {
  const ::tensorflow::boosted_trees::trees::TreeNode* p = split_node_;
  // @@protoc_insertion_point(field_get:tensorflow.boosted_trees.learner.SplitInfo.split_node)
  return p != NULL ? *p : *reinterpret_cast<const ::tensorflow::boosted_trees::trees::TreeNode*>(
      &::tensorflow::boosted_trees::trees::_TreeNode_default_instance_);
}
::tensorflow::boosted_trees::trees::TreeNode* SplitInfo::mutable_split_node() {
  
  if (split_node_ == NULL) {
    _slow_mutable_split_node();
  }
  // @@protoc_insertion_point(field_mutable:tensorflow.boosted_trees.learner.SplitInfo.split_node)
  return split_node_;
}
::tensorflow::boosted_trees::trees::TreeNode* SplitInfo::release_split_node() {
  // @@protoc_insertion_point(field_release:tensorflow.boosted_trees.learner.SplitInfo.split_node)
  
  if (GetArenaNoVirtual() != NULL) {
    return _slow_release_split_node();
  } else {
    ::tensorflow::boosted_trees::trees::TreeNode* temp = split_node_;
    split_node_ = NULL;
    return temp;
  }
}
 void SplitInfo::set_allocated_split_node(::tensorflow::boosted_trees::trees::TreeNode* split_node) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete split_node_;
  }
  if (split_node != NULL) {
    _slow_set_allocated_split_node(message_arena, &split_node);
  }
  split_node_ = split_node;
  if (split_node) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:tensorflow.boosted_trees.learner.SplitInfo.split_node)
}

// .tensorflow.boosted_trees.trees.Leaf left_child = 2;
bool SplitInfo::has_left_child() const {
  return this != internal_default_instance() && left_child_ != NULL;
}
void SplitInfo::clear_left_child() {
  if (GetArenaNoVirtual() == NULL && left_child_ != NULL) delete left_child_;
  left_child_ = NULL;
}
const ::tensorflow::boosted_trees::trees::Leaf& SplitInfo::left_child() const {
  const ::tensorflow::boosted_trees::trees::Leaf* p = left_child_;
  // @@protoc_insertion_point(field_get:tensorflow.boosted_trees.learner.SplitInfo.left_child)
  return p != NULL ? *p : *reinterpret_cast<const ::tensorflow::boosted_trees::trees::Leaf*>(
      &::tensorflow::boosted_trees::trees::_Leaf_default_instance_);
}
::tensorflow::boosted_trees::trees::Leaf* SplitInfo::mutable_left_child() {
  
  if (left_child_ == NULL) {
    _slow_mutable_left_child();
  }
  // @@protoc_insertion_point(field_mutable:tensorflow.boosted_trees.learner.SplitInfo.left_child)
  return left_child_;
}
::tensorflow::boosted_trees::trees::Leaf* SplitInfo::release_left_child() {
  // @@protoc_insertion_point(field_release:tensorflow.boosted_trees.learner.SplitInfo.left_child)
  
  if (GetArenaNoVirtual() != NULL) {
    return _slow_release_left_child();
  } else {
    ::tensorflow::boosted_trees::trees::Leaf* temp = left_child_;
    left_child_ = NULL;
    return temp;
  }
}
 void SplitInfo::set_allocated_left_child(::tensorflow::boosted_trees::trees::Leaf* left_child) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete left_child_;
  }
  if (left_child != NULL) {
    _slow_set_allocated_left_child(message_arena, &left_child);
  }
  left_child_ = left_child;
  if (left_child) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:tensorflow.boosted_trees.learner.SplitInfo.left_child)
}

// .tensorflow.boosted_trees.trees.Leaf right_child = 3;
bool SplitInfo::has_right_child() const {
  return this != internal_default_instance() && right_child_ != NULL;
}
void SplitInfo::clear_right_child() {
  if (GetArenaNoVirtual() == NULL && right_child_ != NULL) delete right_child_;
  right_child_ = NULL;
}
const ::tensorflow::boosted_trees::trees::Leaf& SplitInfo::right_child() const {
  const ::tensorflow::boosted_trees::trees::Leaf* p = right_child_;
  // @@protoc_insertion_point(field_get:tensorflow.boosted_trees.learner.SplitInfo.right_child)
  return p != NULL ? *p : *reinterpret_cast<const ::tensorflow::boosted_trees::trees::Leaf*>(
      &::tensorflow::boosted_trees::trees::_Leaf_default_instance_);
}
::tensorflow::boosted_trees::trees::Leaf* SplitInfo::mutable_right_child() {
  
  if (right_child_ == NULL) {
    _slow_mutable_right_child();
  }
  // @@protoc_insertion_point(field_mutable:tensorflow.boosted_trees.learner.SplitInfo.right_child)
  return right_child_;
}
::tensorflow::boosted_trees::trees::Leaf* SplitInfo::release_right_child() {
  // @@protoc_insertion_point(field_release:tensorflow.boosted_trees.learner.SplitInfo.right_child)
  
  if (GetArenaNoVirtual() != NULL) {
    return _slow_release_right_child();
  } else {
    ::tensorflow::boosted_trees::trees::Leaf* temp = right_child_;
    right_child_ = NULL;
    return temp;
  }
}
 void SplitInfo::set_allocated_right_child(::tensorflow::boosted_trees::trees::Leaf* right_child) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete right_child_;
  }
  if (right_child != NULL) {
    _slow_set_allocated_right_child(message_arena, &right_child);
  }
  right_child_ = right_child;
  if (right_child) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:tensorflow.boosted_trees.learner.SplitInfo.right_child)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace learner
}  // namespace boosted_trees
}  // namespace tensorflow

// @@protoc_insertion_point(global_scope)
